"""Base classes and interfaces for inspection rules."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from pcb_inspector.core.config import InspectorConfig
from pcb_inspector.core.models import Finding, FindingCategory, Severity


class BaseRule(ABC):
    """Abstract base class for all engineering inspection rules."""

    rule_id: str = "BASE-000"
    name: str = "Base Rule"
    category: FindingCategory = FindingCategory.DRC_ERC
    default_severity: Severity = Severity.WARNING
    description: str = "Abstract base rule"

    @abstractmethod
    def evaluate(self, context: Any, config: InspectorConfig) -> list[Finding]:
        """Evaluate the rule against the PCB/Schematic context and return findings.

        Args:
            context: Parsed PCB/Schematic representation or project bundle.
            config: Current inspection configuration and threshold settings.

        Returns:
            List of findings generated by this rule.
        """
        raise NotImplementedError
